"""VWAP Deviation Stop-Hunt Reversal strategy.

Derived from the LuxAlgo TikTok video analysis (see strategy_spec.md).

Entry logic:
    1. Price extends to VWAP +-2 sigma band
    2. Session pivot high/low is swept (stop-run)
    3. Volume at the sweep level >= 1.5x session average
    4. Buyer/seller classification confirms passive side absorbing
    5. Engulfing confirmation candle on 5M (or bar timeframe)

Exit logic:
    TP1 = VWAP (close 50%)
    TP2 = opposite VWAP band (close remaining)
    SL  = beyond sweep extreme + 2 ticks buffer
    Time-stop = 10 bars without hitting TP1
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum

import numpy as np
import polars as pl

logger = logging.getLogger(__name__)


class Side(Enum):
    LONG = 1
    SHORT = -1


@dataclass
class Signal:
    """A trading signal generated by the strategy."""

    bar_idx: int
    ts: int  # nanosecond timestamp
    side: Side
    entry_price: float
    stop_loss: float
    tp1: float  # VWAP
    tp2: float  # opposite band
    sweep_price: float  # the swept pivot level
    volume_ratio: float  # volume multiplier at sweep level
    buyer_seller: str  # 'B' or 'S'
    reason: str = ""


@dataclass
class StrategyConfig:
    """Tunable parameters for the strategy."""

    # VWAP
    vwap_num_deviations: float = 2.0

    # Pivots
    pivot_lookback: int = 20

    # Volume
    volume_ratio_min: float = 1.5  # minimum golden bar multiplier

    # Entry
    require_engulfing: bool = True  # require engulfing candle for confirmation

    # Exit
    sl_buffer_ticks: int = 2  # ticks beyond sweep extreme
    tp1_pct: float = 0.5  # fraction to close at TP1
    time_stop_bars: int = 10  # max bars to hold without TP1

    # Tick size (set per instrument)
    tick_size: float = 0.25


def generate_signals(
    bars: pl.DataFrame,
    config: StrategyConfig | None = None,
) -> list[Signal]:
    """Scan prepared bars for strategy signals.

    The input `bars` DataFrame must already have these columns (from features.py):
        open, high, low, close, volume,
        vwap, vwap_upper, vwap_lower,
        pivot_high_level, pivot_low_level,
        sweep_high, sweep_low,
        bullish_engulfing, bearish_engulfing,
        bar_volume_ratio (optional — volume ratio at the bar's price range),
        buyer_seller_flag (optional — 'B' or 'S' dominant at this bar)

    Returns list of Signal objects.
    """
    if config is None:
        config = StrategyConfig()

    signals: list[Signal] = []
    required = {"vwap", "vwap_upper", "vwap_lower", "sweep_high", "sweep_low"}
    missing = required - set(bars.columns)
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    has_engulfing = "bullish_engulfing" in bars.columns
    has_vol_ratio = "bar_volume_ratio" in bars.columns
    has_bs_flag = "buyer_seller_flag" in bars.columns

    for i, row in enumerate(bars.iter_rows(named=True)):
        # ── LONG SIGNAL ──────────────────────────────────────────────
        if row["sweep_low"]:
            # Check: price at or below lower VWAP band
            if row["low"] > row["vwap_lower"]:
                continue

            # Check: volume ratio (if available)
            vol_ratio = row.get("bar_volume_ratio", 2.0)
            if has_vol_ratio and vol_ratio < config.volume_ratio_min:
                continue

            # Check: buyer dominance (if available)
            bs_flag = row.get("buyer_seller_flag", "B")
            if has_bs_flag and bs_flag != "B":
                continue

            # Check: engulfing confirmation (if required)
            if config.require_engulfing and has_engulfing:
                if not row.get("bullish_engulfing", False):
                    continue

            # Build signal
            sweep_extreme = row["low"]
            sl = sweep_extreme - config.sl_buffer_ticks * config.tick_size
            entry = row["close"]
            tp1 = row["vwap"]
            tp2 = row["vwap_upper"]

            # Sanity: TP must be above entry, SL below
            if tp1 <= entry or sl >= entry:
                continue

            signals.append(
                Signal(
                    bar_idx=i,
                    ts=row.get("ts_event", 0),
                    side=Side.LONG,
                    entry_price=entry,
                    stop_loss=sl,
                    tp1=tp1,
                    tp2=tp2,
                    sweep_price=row.get("pivot_low_level", sweep_extreme),
                    volume_ratio=vol_ratio,
                    buyer_seller=bs_flag,
                    reason=f"Sweep LOW at {sweep_extreme:.2f}, vol={vol_ratio:.1f}x, {bs_flag}",
                )
            )

        # ── SHORT SIGNAL ─────────────────────────────────────────────
        if row["sweep_high"]:
            if row["high"] < row["vwap_upper"]:
                continue

            vol_ratio = row.get("bar_volume_ratio", 2.0)
            if has_vol_ratio and vol_ratio < config.volume_ratio_min:
                continue

            bs_flag = row.get("buyer_seller_flag", "S")
            if has_bs_flag and bs_flag != "S":
                continue

            if config.require_engulfing and has_engulfing:
                if not row.get("bearish_engulfing", False):
                    continue

            sweep_extreme = row["high"]
            sl = sweep_extreme + config.sl_buffer_ticks * config.tick_size
            entry = row["close"]
            tp1 = row["vwap"]
            tp2 = row["vwap_lower"]

            if tp1 >= entry or sl <= entry:
                continue

            signals.append(
                Signal(
                    bar_idx=i,
                    ts=row.get("ts_event", 0),
                    side=Side.SHORT,
                    entry_price=entry,
                    stop_loss=sl,
                    tp1=tp1,
                    tp2=tp2,
                    sweep_price=row.get("pivot_high_level", sweep_extreme),
                    volume_ratio=vol_ratio,
                    buyer_seller=bs_flag,
                    reason=f"Sweep HIGH at {sweep_extreme:.2f}, vol={vol_ratio:.1f}x, {bs_flag}",
                )
            )

    logger.info("Generated %d signals (%d long, %d short)",
                len(signals),
                sum(1 for s in signals if s.side == Side.LONG),
                sum(1 for s in signals if s.side == Side.SHORT))
    return signals


def prepare_bars(
    bars: pl.DataFrame,
    trades: pl.DataFrame | None = None,
    config: StrategyConfig | None = None,
    tick_size: float = 0.25,
) -> pl.DataFrame:
    """Full pipeline: take raw OHLCV bars and add all strategy features.

    This is the convenience function that chains all feature computations.
    """
    from . import features

    if config is None:
        config = StrategyConfig(tick_size=tick_size)

    # 1. VWAP (computed from bars as proxy — ideally from trades)
    df = bars.with_columns(
        (pl.col("volume") * (pl.col("high") + pl.col("low") + pl.col("close")) / 3)
        .cum_sum()
        .alias("_cum_pv"),
        pl.col("volume").cum_sum().alias("_cum_vol"),
    ).with_columns(
        (pl.col("_cum_pv") / pl.col("_cum_vol")).alias("vwap"),
    )

    # VWAP deviation
    typical_price = (pl.col("high") + pl.col("low") + pl.col("close")) / 3
    df = df.with_columns(
        (typical_price.pow(2) * pl.col("volume")).cum_sum().alias("_cum_p2v"),
    ).with_columns(
        (
            (pl.col("_cum_p2v") / pl.col("_cum_vol")) - pl.col("vwap").pow(2)
        ).clip(lower_bound=0).sqrt().alias("vwap_dev"),
    ).with_columns(
        (pl.col("vwap") + config.vwap_num_deviations * pl.col("vwap_dev")).alias("vwap_upper"),
        (pl.col("vwap") - config.vwap_num_deviations * pl.col("vwap_dev")).alias("vwap_lower"),
    ).drop("_cum_pv", "_cum_vol", "_cum_p2v")

    # 2. Pivots
    df = features.detect_pivots(df, lookback=config.pivot_lookback)

    # 3. Sweeps
    df = features.detect_sweeps(df)

    # 4. Engulfing candles
    df = features.detect_engulfing(df)

    return df
